# Generated by Django 5.1.3 on 2024-12-27 16:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_alter_emp_comm_alter_emp_mgr'),
    ]

    operations = [
        migrations.AlterField(
            model_name='emp',
            name='mgr',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='app.emp'),
        ),
    ]
