# Generated by Django 5.1.3 on 2024-12-28 10:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_alter_emp_mgr'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='emp',
            name='mgr',
        ),
    ]
